### ISSUE TITLE
modal for mobile device

### ISSUE THREAD

**Issue by jindev** [zxdong262/zui#3]
hi zxdong262 

i use this for webview on andorid app. 
everything is ok but there is a one problem.
it cant get height when use $(window).height so i suggest screen.height.

thx

**Comment by zxdong262** [comment]
thanks anyway, but actrually it is more suitable for desktop browsers.

there is a mobile version: mui

http://html5beta.com/mui/

or better just use other ui framework, I have not maintain the code, must be some bugs there.
